language: node_js

node_js:
  - 16

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

script:
  - eslint 'src/**'
  - yarn test:coveralls
